
export const strings = {
  hindi: {
    appName: 'GST Saathi',
    tagline: 'Aapka GST, aasaan bhasha mein',
    loading: 'Loading...',
    selectLanguage: 'Apni bhasha chunein',
    continueBtn: 'Aage badhein →',
    enterPhone: 'Apna number darj karein',
    phoneSubtext: 'Login aur signup dono isi se hoga',
    sendOtp: 'OTP bhejo',
    verifyOtp: 'Verify karo ✓',
    enterGstin: 'Apna GSTIN darj karein',
    gstinSubtext: 'Yeh 15 digit ka number aapke GST certificate pe hota hai',
    businessFound: 'Dukaan mil gayi!',
    confirmBusiness: 'Haan, sahi hai ✓',
    rejectBusiness: 'Nahi, dobara dalunga',
    whatDoYouSell: 'Aap kya bechte hain?',
    categorySubtext: 'Isse hum sahi HSN codes dhundhenge',
    letsStart: 'Shuru karein! →',
    speakOrder: 'Bolo — aaj kya becha?',
    listening: 'Sun raha hoon...',
    confirmOrder: 'Haan, sahi hai ✓',
    retryOrder: 'Dobara bolo 🎙️',
    invoiceReady: 'Invoice tayaar hai!',
    sendWhatsapp: '📱 WhatsApp pe bhejo',
    saveInvoice: '💾 Save karo',
    dashboardGreeting: 'Namaste',
    deadlineCard: 'GSTR-1 ka deadline',
    billsTab: 'Bills',
    returnsTab: 'Returns',
    alertsTab: 'Alerts',
    homeTab: 'Home',
    recentActivity: 'Recent Activity',
    viewAll: 'Sab dekho',
    scanBill: 'Bill scan ho gaya!',
    confirmBill: 'Bill confirm karo ✓',
    editBill: 'Kuch edit karna hai',
    alertsTitle: 'Alerts',
    fileNow: 'File karo →',
    filingTitle: 'April 2024 ka GST',
    youMustPay: 'AAPKO BHARNA HAI',
    congratulations: 'Badhai ho! 🎉',
    filedSuccess: 'April ka GST bhar diya!',
    homeScreen: '🏠 Home Screen',
    doAgain: 'Dobara entry karo',
    goingHome: 'seconds mein home screen pe jaenge',
  },
  marathi: {
    appName: 'GST Saathi',
    tagline: 'तुमचा GST, सोप्या भाषेत',
    loading: 'लोड होत आहे...',
    selectLanguage: 'तुमची भाषा निवडा',
    continueBtn: 'पुढे जा →',
    enterPhone: 'तुमचा नंबर टाका',
    phoneSubtext: 'लॉगिन आणि साइनअप दोन्ही यातून होईल',
    sendOtp: 'OTP पाठवा',
    verifyOtp: 'Verify करा ✓',
    enterGstin: 'तुमचा GSTIN टाका',
    gstinSubtext: 'हा 15 अंकी नंबर तुमच्या GST प्रमाणपत्रावर आहे',
    businessFound: 'दुकान सापडले!',
    confirmBusiness: 'हो, बरोबर आहे ✓',
    rejectBusiness: 'नाही, परत टाकतो',
    whatDoYouSell: 'तुम्ही काय विकता?',
    categorySubtext: 'यावरून आम्ही योग्य HSN codes शोधू',
    letsStart: 'सुरू करूया! →',
    speakOrder: 'बोला — आज काय विकले?',
    listening: 'ऐकत आहे...',
    confirmOrder: 'हो, बरोबर आहे ✓',
    retryOrder: 'परत बोला 🎙️',
    invoiceReady: 'Invoice तयार आहे!',
    sendWhatsapp: '📱 WhatsApp वर पाठवा',
    saveInvoice: '💾 Save करा',
    dashboardGreeting: 'नमस्कार',
    deadlineCard: 'GSTR-1 ची deadline',
    billsTab: 'Bills',
    returnsTab: 'Returns',
    alertsTab: 'Alerts',
    homeTab: 'Home',
    recentActivity: 'अलीकडील व्यवहार',
    viewAll: 'सर्व पहा',
    scanBill: 'Bill scan झाले!',
    confirmBill: 'Bill confirm करा ✓',
    editBill: 'काही बदलायचे आहे',
    alertsTitle: 'Alerts',
    fileNow: 'File करा →',
    filingTitle: 'April 2024 चा GST',
    youMustPay: 'तुम्हाला भरायचे आहे',
    congratulations: 'अभिनंदन! 🎉',
    filedSuccess: 'April चा GST भरला!',
    homeScreen: '🏠 Home Screen',
    doAgain: 'परत entry करा',
    goingHome: 'seconds मध्ये home screen वर जाऊ',
  },
  telugu: {
    appName: 'GST Saathi',
    tagline: 'మీ GST, సులభమైన భాషలో',
    loading: 'లోడ్ అవుతోంది...',
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    continueBtn: 'ముందుకు వెళ్ళండి →',
    enterPhone: 'మీ నంబర్ నమోదు చేయండి',
    phoneSubtext: 'లాగిన్ మరియు సైన్అప్ రెండూ దీని ద్వారా జరుగుతాయి',
    sendOtp: 'OTP పంపండి',
    verifyOtp: 'Verify చేయండి ✓',
    enterGstin: 'మీ GSTIN నమోదు చేయండి',
    gstinSubtext: 'ఈ 15 అంకెల నంబర్ మీ GST సర్టిఫికేట్ పై ఉంటుంది',
    businessFound: 'దుకాణం దొరికింది!',
    confirmBusiness: 'అవును, సరైనది ✓',
    rejectBusiness: 'కాదు, మళ్ళీ నమోదు చేస్తాను',
    whatDoYouSell: 'మీరు ఏమి అమ్ముతారు?',
    categorySubtext: 'దీని ద్వారా మేము సరైన HSN codes కనుగొంటాము',
    letsStart: 'ప్రారంభిద్దాం! →',
    speakOrder: 'చెప్పండి — ఈరోజు ఏమి అమ్మారు?',
    listening: 'వింటున్నాను...',
    confirmOrder: 'అవును, సరైనది ✓',
    retryOrder: 'మళ్ళీ చెప్పండి 🎙️',
    invoiceReady: 'Invoice సిద్ధంగా ఉంది!',
    sendWhatsapp: '📱 WhatsApp లో పంపండి',
    saveInvoice: '💾 Save చేయండి',
    dashboardGreeting: 'నమస్కారం',
    deadlineCard: 'GSTR-1 గడువు',
    billsTab: 'Bills',
    returnsTab: 'Returns',
    alertsTab: 'Alerts',
    homeTab: 'Home',
    recentActivity: 'ఇటీవలి లావాదేవీలు',
    viewAll: 'అన్నీ చూడండి',
    scanBill: 'Bill scan అయింది!',
    confirmBill: 'Bill confirm చేయండి ✓',
    editBill: 'ఏదైనా మార్చాలి',
    alertsTitle: 'Alerts',
    fileNow: 'File చేయండి →',
    filingTitle: 'April 2024 GST',
    youMustPay: 'మీరు చెల్లించాలి',
    congratulations: 'అభినందనలు! 🎉',
    filedSuccess: 'April GST చెల్లించారు!',
    homeScreen: '🏠 Home Screen',
    doAgain: 'మళ్ళీ entry చేయండి',
    goingHome: 'seconds లో home screen కి వెళ్తాము',
  }
}
